---
abstract: 'Handy web browsing in a Perl object'
author:
  - 'Andy Lester <andy at petdance.com>'
build_requires:
  CGI: '4.32'
  Encode: '0'
  Exporter: '0'
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  HTTP::Daemon: '0'
  HTTP::Response: '0'
  HTTP::Server::Simple::CGI: '0'
  LWP: '0'
  LWP::Simple: '0'
  Test::More: '0'
  Test::RequiresInternet: '0'
  URI: '0'
  URI::Escape: '0'
  bytes: '0'
  constant: '0'
  lib: '0'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.006, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Mechanize
no_index:
  directory:
    - examples
    - t
    - xt
requires:
  Carp: '0'
  Getopt::Long: '0'
  HTML::Form: '1.00'
  HTML::HeadParser: '0'
  HTML::TokeParser: '0'
  HTML::TreeBuilder: '0'
  HTTP::Cookies: '0'
  HTTP::Request: '1.30'
  HTTP::Request::Common: '0'
  LWP::UserAgent: '5.827'
  Pod::Usage: '0'
  URI::URL: '0'
  URI::file: '0'
  base: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/libwww-perl/WWW-Mechanize/issues
  homepage: https://github.com/libwww-perl/WWW-Mechanize
  repository: https://github.com/libwww-perl/WWW-Mechanize.git
version: '1.77'
x_contributors:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
  - 'Andy Lester <andy@petdance.com>'
  - 'dakkar <dakkar@thenautilus.net>'
  - 'David Precious <davidp@preshweb.co.uk>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Flavio Poletti <flavio@polettix.it>'
  - 'Florian Schlichting <fsfs@debian.org>'
  - 'Gabor Szabo <szabgab@gmail.com>'
  - 'Jason May <jasonmay@bestpractical.com>'
  - 'Jesse Vincent <jesse@bestpractical.com>'
  - 'Karen Etheridge <ether@cpan.org>'
  - "Kirrily 'Skud' Robert <skud@infotrope.net>"
  - 'Lars Dɪᴇᴄᴋᴏᴡ 迪拉斯 <daxim@cpan.org>'
  - 'Mark Stosberg <mark@summersault.com>'
  - 'Matt S Trout <mst@shadowcat.co.uk>'
  - 'Max Maischein <corion@cpan.org>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'sunnavy <sunnavy@bestpractical.com>'
  - 'Zefram <zefram@fysh.org>'
x_serialization_backend: 'YAML::Tiny version 1.69'
