--- #YAML:1.0
name:                WWW-Mechanize
version:             1.49_01
abstract:            Handy web browsing in a Perl object
license:             ~
author:              
    - Andy Lester <andy@petdance.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    File::Temp:                    0
    FindBin:                       0
    Getopt::Long:                  0
    HTML::Form:                    1.038
    HTML::HeadParser:              0
    HTML::Parser:                  3.33
    HTML::TokeParser:              2.28
    HTTP::Daemon:                  0
    HTTP::Request:                 1.3
    HTTP::Response::Encoding:      0.05
    HTTP::Status:                  0
    LWP:                           5.815
    LWP::UserAgent:                5.815
    Pod::Usage:                    0
    Test::More:                    0.34
    URI:                           1.25
    URI::file:                     0
    URI::URL:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
